app/home/forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, SubmitField, DateField, IntegerField
from wtforms.validators import DataRequired
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from ..models import Department, Role, Record

class RecordForm(FlaskForm):
    """
    Form for workers to add or add Records
    """

    name = StringField('Name', validators = [DataRequired()])
    day = DateField('Date', validators = [DataRequired()])
    production = IntegerField('production', validators = [DataRequired()] )
    opening = IntegerField('opening count', validators = [DataRequired()] )
    closing = IntegerField('closing count', validators = [DataRequired()] )

    submit = SubmitField('Submit')

app/home/__init__.py
from flask import Blueprint


home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import abort, render_template

from flask_login import current_user ,login_required

from . import home
from ..models import Record
from forms import RecordForm


@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """

    return render_template('index.html', title = "Welcome")

@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """

    return render_template('home/dashboard.html', title = "Dashboard")
##--------------------------------------------------------------------------------
#### Records route
##--------------------------------------------------------------------------------
@home.route('/record', methods=['GET', 'POST'])
@login_required
def add_record():

    add_department = True

    form = RecordForm()
    if form.validate_on_submit():
        record = Record(name=form.name.data,
                            day = form.day.data,
                            production= form.production.data,
                            opening = form.opening.data,
                            closing = form.closing.data
                            )
        try:
            # add department to the database
            db.session.add(record)
            db.session.commit()
            flash('You have successfully added a new department.')
        except:
            # in case department name already exists
            flash('Error: department name already exists.')

        # redirect to departments page
        return redirect(url_for('admin.list_departments'))

    # load department template
    return render_template('home/record.html', action="Add",
                           add_record=add_record, form=form,
                           title="Add Record")




@home.route('/records',  methods=['GET', 'POST'])
@login_required
def records():
    """
    List all departments
    """

    records = Record.query.all()

    return render_template('home/records.html',
                           records=records, title="Records")

@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    #prevent non_admins from accessing the page
    if not current_user.is_admin:
        abort(403)
    return render_template('home/admin_dashboard.html')

app/templates/home/admin_dashboard.html
{% extends "base.html" %}
{% block title %}Admin Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Admin Dashboard</h1>
                    <h3>For administrators only!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>The Dashboard</h1>
                    <h3>We made it here!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/record.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_department %}
        Add Department
    {% else %}
        Edit Department
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_department %}
                <h1>Add Department</h1>
            {% else %}
                <h1>Edit Department</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/records.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Departments{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Records</h1>
        {% if departments %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> Name </th>
                  <th width="40%"> Description </th>
                  <th width="15%"> Employee Count </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for record in records %}
                <tr>
                  <td> {{ record.worker_name }} </td>
                  <td> {{ record.day }} </td>
                  <td>

                  </td>
                  <td>
                    <a href="{{ url_for('admin.edit_department', id=record.id) }}">
                      <i class="fa fa-pencil"></i> Edit
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('admin.delete_department', id=record.id) }}">
                      <i class="fa fa-trash"></i> Delete
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No departments have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('home.add_record') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Record
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}